### ISSUE TITLE
When using the plugin the maximum quality is 720p

### ISSUE THREAD

**Issue by michiel2304** [pixeltris/TwitchAdBlock#1]
As the title states, when i use the plugin i only get 720p as the maximum quality option.

When i disable the extension i see the higher quality options again.

**Comment by pixeltris** [comment]
This should fix the source quality option. Can you confirm it now works as expected?
 https://github.com/pixeltris/TwitchAdBlock/commit/100cc911269aed42ea42ef5db9600bdfda726d05

**Comment by michiel2304** [comment]
It seems to be working now! Great! BTW, u know any easy way of disabling the chrome notification to disable devoloper mode?

**Comment by pixeltris** [comment]
Unfortunately I don't think there is an easy way to do that anymore. Feel free to submit the extension to the chrome store so you don't need to use developer mode.
