### ISSUE TITLE
Player stops when I switch to other tab

### ISSUE THREAD

**Issue by chtat12** [pixeltris/TwitchAdBlock#3]
Right now the player stops playing if I switch to other tab. Is there a way to keep the stream going, even if it's not in the current tab?

**Comment by pixeltris** [comment]
I'm not able to reproduce this. In chrome the twitch player will pause the stream if the player is muted and in a different tab, then it will resume it when you go back to that tab. That happens regardless of whether this extension is enabled.

Does the player behave as desired when the extension is disabled? If so which OS / browser version are you running and what are the exact steps to reproduce the error.

**Comment by chtat12** [comment]
You are right. This behavior occurs even if the extension is disabled.

For some reason, I am now able to keep the player playing if I keep the volume > 0% (not muted). I'm pretty sure this doesn't work until a few days ago. 

I'm using windows 10 + FF 57.0.4 for reference.
