### ISSUE TITLE
Broken on FF 57.0.4 & Chrome 63.0.3239.132

### ISSUE THREAD

**Issue by No-Worky** [pixeltris/TwitchAdBlock#4]
Thanks for making this addon. I was looking forward to using it but sadly it doesn't seem to be working on the latest Firefox or Chrome builds. No ads load but more importantly, the stream window stays black and doesn't load. It shows LIVE in the top right and lets me pause/play but it looks like the extension blocks the stream from loading. Hope you can patch

**Comment by pixeltris** [comment]
It is working for me on the latest chrome. I haven't tested firefox.

If you see pause/play buttons but no stream that means the player.js was redirected but something broke on the url modifier for the stream url. Try opening chrome, loading a stream, opening the developer console, select the "Console" tab and then in the filter bar at the top of the console tab enter "redirect" which should filter errors coming from redirect.js.

**Comment by No-Worky** [comment]
Thanks for the response. I downloaded and installed the extension for Chrome again and it seems to be working now, odd. The issue persists with Firefox but switching over to HTML5 player using the twitch settings cogwheel seems to have fixed that.
