### ISSUE TITLE
Manifest is not valid JSON. Line: 7, column: 2, Unexpected token.

### ISSUE THREAD

**Issue by bobsage123** [pixeltris/TwitchAdBlock#6]
Getting this when trying to import into chrome. I saw another person with this issue but it was closed and I don't see a solution listed. I'm sorry if the fix is obvious but i'm stumped. Thanks.

**Comment by pixeltris** [comment]
Did you find a solution? I think that happens if you right click and save the files directly from the main repository. Try downloading the latest archive and take the two files from there instead https://github.com/pixeltris/TwitchAdBlock/archive/master.zip

**Comment by bobsage123** [comment]
That worked, thanks!
