### ISSUE TITLE
chrome keeps asking to disable extensions that are in developer mode

### ISSUE THREAD

**Issue by thegitfather** [pixeltris/TwitchAdBlock#8]
is there an easy way to disable that notification? maybe its better to publish a grease/tampermonkey script?

**Comment by decimic** [comment]
This article will tell you how: https://www.ghacks.net/2017/07/04/hide-chromes-disable-developer-mode-extensions-warning/

You can also use Chromium (https://chromium.woolyss.com/), but you'll have to manually update Chromium when a new version comes out.
